[tool.poetry]
name = "regression-project"
version = "1.0.0"
description = "Machine Learning Regression Module"
authors = ["mnassiri"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^1.26.0"
matplotlib = "^3.8.0"
scikit-learn = "^1.3.0"
pandas = "^2.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
